### ISSUE TITLE
Ser2net Make Fails

### ISSUE THREAD

**Issue by timbarnhart** [Pack3tL0ss/ConsolePi#2]
Just installed ConsolePi on the latest Raspbian.  Got an error during the install script that ser2net make failed.  Ran apt-get install ser2net, then re-ran script and was able to successfully complete the install.

**Comment by Pack3tL0ss** [comment]
Thanks for taking the time to report the issue.

yeah `apt-get install ser2net` is fine for a fallback, the installer builds ser2net from source which is a far more recent version than what's available from apt.  ConsolePi is not handicapped in anyway none of the features available from the more recent versions are utilized by the install script.  I only built from source so users would have the most recent in case they wanted to do something custom (custom ser2net.conf utilizing whatever features...).  

If you don't mind:
- What model/generation of RaspberryPi
- Current version of raspbian?
- Assume the pi had internet access the entire time.

Lastly if you have the install.log (or install.log.#) files.  I should be able to get the full error details from it.  
Given you re-ran the installer the original error should be rolled into install.log.1  the logs are in /etc/ConsolePi/installer/

Thx

**Comment by timbarnhart** [comment]
Absolutely!  Thanks for making this!!

 Answers inline below.

Question:
                What is the proper syntax to telnet directly into one of the devices?  When I try – “telnet 192.168.100.23 8001” or use putty/SecurCRT, I get a connection refused.
                If I ssh into the pi and run the menu, I can access the devices fine.


Thanks again!

Tim

**Comment by Pack3tL0ss** [comment]
Yes that syntax should be correct.  With 1 device plugged in you should be able to telnet to port 8001.
The fact Consolepi-menu presents the menu option and you can connect indicates there is no issue recognizing the USB-serial adapter.  So that's good.

Make sure ser2net is running `systemctl status ser2net` and/or `ps aux |grep -v grep |grep ser2net`

It may be that ser2net has it's default config because install from source failed in the installer.  I would have expected it to place the ConsolePi config for ser2net when you ran the installer after installing ser2net via apt, but that's not a scenario I tested so maybe not.

The ConsolePi config file for ser2net is in /etc/ConsolePi/src/ser2net.conf just cp it over to /etc
`sudo cp /etc/ConsolePi/src/ser2net.conf /etc`
_You can backup whatever original is there prior to cp if you like the cp will overwrite the original_

Then: ```
sudo systemctl stop ser2net
sudo systemctl staart ser2net
systemctl status ser2net```

It may also be a firewall issue.  I tested with the raspian-light version (no desktop environment), wouldn't expect many differences for what ConsolePi does, but maybe... You can check firewall rules with `sudo iptables -L`  

I'll test to see what's up with the ser2net error when I get a chance.

**Comment by timbarnhart** [comment]
Copying the ser2net.conf file did the trick!  Should have thought of that myself…

Where can I see the pushbullet config?  I want to add that to some of my other Pi’s.  That’s an awesome utility to have.

**Comment by Pack3tL0ss** [comment]
Cool Glad it's sorted.

The code for PushBullet is pretty simple, it's just a curl command.  It's in the /etc/ConsolePi/ConsolePi.sh script.  in the Push() function (line 53).

**Comment by Pack3tL0ss** [comment]
Fixed - Updated url used to get ser2net from source.  It had changed to point to another project by the same author.  installer now configured to get ser2net 3.5.1 vs using "latest".
